language: java

jdk:
  - oraclejdk8
  
  
addons:
  sonarcloud:
    organization: "remartins-github" # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN2}
    

script: 
  - mvn package
  - mvn cobertura:cobertura
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
script: 
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar  
